spring.application.name=expenseTracker
server.port=9595
spring.datasource.url=jdbc:postgresql://localhost:5432/expenseTracker
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update